version: '3'
services:
  python-practice:
    container_name: python-practice
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
     - "5000:5000"
    image: rahullodha85/python-practice_web
    depends_on:
      - influxdb
    links:
      - influxdb

  influxdb:
    container_name: influxdb
    ports:
      - 8086:8086
    image: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    container_name: grafana
    ports:
      - 3000:3000
    image: grafana/grafana
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - influxdb
    links:
      - influxdb