pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image'
                script {
                    app = docker.build('edinpark/python-practice')
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                echo 'Pushing Docker Image to DockerHub'
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub'){
                        app.push('123456')
                        app.push('latest')
                    }
                }
            }
        }
    }
}