pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image'
                sh 'echo whoami'
                sh 'whoami'
                echo 'whoami'
                script {
                    app = docker.build('rahullodha85/python-practice')
                }
            }
        }
    }
}